model.products = [
    
    // Stue
    {
        title: 'Sofa',
        price: 6999,
        stock: 3,
        totalProducts: 3,
        category: 'Stue',
        id: 111,
        parentId: 11,
        subCategory: 'Sofa',
        img: 'TempBilder/1Stue/1Sofa/vintagesofaoker.jpeg',
        description: 'Pent brukt, men fortsatt en flott toseter sofa. Stått lagret i bod siden 2005. Sofaen ble laget i Danmark, og ble lansert i 1978.',
        measures: 'Høyde: 80cm. Dybde: 50cm. Lengde: 170cm',
        color: ['Oker Gul'],
        country: 'Danmark',
        year: "1978",
        productQuantity: 0,
    },
    {
        title: 'Spisestuestol',
        price: 1999,
        stock: 4,
        totalProducts: 4,
        category: 'Spiserom',
        id: 128,
        parentId: 22,
        subCategory: 'Spisestuestol',
        img: 'TempBilder/2Spiserom/1stoler/habdulstol.png',
        description: 'Godt brukt stol, men fortsatt flott å se på. Denne stolen er robust og tåler en del. En klassiker som aldri går av moten. Den ble laget i Tyskland, og ble lansert rundt 1967.',
        measures: 'Høyde: 80cm. Dybde: 40cm. Lengde: 40cm',
        color: ['Brunt tre'],
        country: 'Tyskland',
        year: "1967",
        productQuantity: 0,

    },
    {
        title: 'Kjøkkenbord',
        price: 2499,
        stock: 5,
        totalProducts: 5,
        category: 'Kjøkken',
        id: 131,
        parentId: 31,
        subCategory: 'Kjøkkenbord',
        img: 'TempBilder/1 Kjøkkenbord/vintagekjokkenbord.jpeg',
        description: 'Rustikk og robust kjøkkenbord. Ser brukt ut, men det er litt av sjarmen. Dette bordet tåler litt, og vil også passe perfekt hos en småbarnsfamilie. Bordet er lansert i 1998, og ble laget i Norge.',
        measures: 'Høyde: 80cm. Dybde: 50cm. Lengde: 170cm',
        color: ['Trehvit'],
        country: 'Norge',
        year: "1998",
        productQuantity: 0,
    },
    {
        title: 'Unikt barbord',
        price: 6799,
        stock: 2,
        totalProducts: 2,
        category: 'Lesesal',
        id: 193,
        parentId: 93,
        subCategory: 'Bord',
        img: 'TempBilder/3Kjøkken/Tempkitchentable/8729f31b63ae4f033a520009b94acd6048-removebg-preview.png',
        description: 'Bardisk med plass til både flasker og glass, også med kjøleboks. Stamme i svart metall med fine kontraster til den gyldne fargen. Topplate av mangotre. Artisten er svensk, og bordet ble originalt utgitt ca 1961.',
        measures: 'Høyde: 100cm. Dybde: 45cm. Lengde: 110cm.',
        color: ['Eik', ' Sort'],
        country: 'Sverige',
        year: '1961',
        productQuantity: 0,
        
    },
    // Soverom
    {
        title: 'Seng',
        price: 8499,
        stock: 3,
        totalProducts: 3,
        category: 'Soverom',
        id: 141,
        parentId: 41,
        subCategory: 'Seng',
        img: 'TempBilder/4 Soverom/1 Seng/vintageseng2.jpeg',
        description: 'Flott, unik seng. Sengen har flotte detaljer og er utformet i smijern. Den er solid og et flott stykke kunst på soverommet. Sengen kommer fra Canada og ble lansert ca 1968.',
        measures: 'Høyde: 105cm. Bredde: 180cm. Lengde: 210cm.',
        color: ['Svart', 'Smijern'],
        country: 'Canada',
        year: '1968',
        productQuantity: 0,
    },

    // Kjøkken

    {
        title: 'Sofabord',
        price: 3399,
        stock: 2,
        totalProducts: 2,
        category: 'Stue',
        id: 122,
        parentId: 12,
        subCategory: 'Sofabord',
        img: 'TempBilder/1Stue/2Sofabord/80svintagebord.jpeg',
        description: 'To små, enkle sofabord, i fin stand. Disse bordene var en klassiker på 70-tallet. Velfungerende om man har mindre plass, eller bare har sansen for tidløse klassikere. Bordene er laget i Spania og utgitt ca 1971.',
        measures: 'Høyde: 40cm. Dybde: 50cm.',
        color: ['Treverk'],
        country: 'Spania',
        year: '1971',
        productQuantity: 0,
    },
    {
        title: 'Kommode',
        price: 2499,
        stock: 1,
        totalProducts: 1,
        category: 'Soverom',
        id: 143,
        parentId: 43,
        subCategory: 'Kommode',
        img: 'TempBilder/1Stue/4Kommoder/kommodevin.jpeg',
        description: 'Fin kommode i god stand. Kommoden har 4 romslige skuffer, så det er plass til oppbevaring. Fin å ha på soverommet, for eksempel. Kommoden kommer fra Danmark, ca 1973.',
        measures: 'Høyde: 80cm. Dybde: 50cm. Lengde: 90cm.',
        color: ['Treverk'],
        country: 'Danmark',
        year: '1973',
        productQuantity: 0,
    },
    {
        title: 'Skjenk ',
        price: 3299,
        stock: 2,
        totalProducts: 2,
        category: 'Spiserom',
        id: 150,
        parentId: 25,
        subCategory: 'Skjenk',
        img: 'TempBilder/1Stue/4Kommoder/retroskjenk.jpeg',
        description: 'Godt brukt, men i god stand. Skjenken har god plass til oppbevaring. Passer for eksempel fint inn i spiserommet. Skjenken kommer fra Danmark og er lansert i 1989.',
        measures: 'Høyde: 85cm. Dybde: 45cm. Bredde: 100cm.',
        color: ['Treverk'],
        country: 'Danmark',
        year: '1989',
        productQuantity: 0,
    },
    {
        title: 'Sofabord',
        price: 2999,
        stock: 1,
        totalProducts: 1,
        category: 'Stue',
        id: 123,
        parentId: 12,
        subCategory: 'Sofabord',
        img: 'TempBilder/2 Sofabord/vintagebordwood.webp',
        description: 'Veldig pent brukt. Stått på et gjesterom, så det er i god stand. Bordet er solid tre. Laget i Sveits, utgitt ca 1992.',
        measures: 'Lengde 90cm. Dybde: 70cm. Høyde: 55cm',
        color: ['Treverk'],
        country: 'Sveits',
        year: '1992',
        productQuantity: 0,
    },
    {
        title: 'Støvletter',
        price: 1999,
        stock: 1,
        totalProducts: 1,
        category: 'Sko',
        id: 181,
        parentId: 81,
        subCategory: 'Støvletter',
        img: 'TempBilder/8Sko/1 Støvletter/stovletter.webp',
        description: 'Ser ut som disse er brukt et par ganger. Helt fine, god stand. Støvlettene er produsert i Polen ca 1990.',
        measures: 'Størrelse: 38.',
        color: ['Turkis', 'Sort'],
        country: 'Polen',
        year: '1990',
        productQuantity: 0,
    },
    {
        title: 'Whiskeysett Globus',
        price: 4999,
        stock: 2,
        totalProducts: 2,
        category: 'Lesesal',
        id: 194,
        parentId: 94,
        subCategory: 'Interiør',
        img: 'TempBilder/2Spiserom/5Pyntegjenstander/vintagekaraffel.jpeg',
        description: 'Hele verden rundt siden 1980. Whiskeysettet er et flott pynte-objekt. Eller et stilig kunststykke å servere gjestene med. Settet er laget i Skottland og utgitt ca 1980.',
        measures: 'Høyde: ca 25cm. ',
        color: ['black', 'brown', 'tan'],
        country: 'Skottland',
        year: '1980',
        productQuantity: 0,
    },
    {
        title: 'Unikt Mosaikk Sofabord',
        price: 6999,
        stock: 2,
        totalProducts: 2,
        category: 'Stue',
        id: 124,
        parentId: 12,
        subCategory: 'Sofabord',
        img: 'TempBilder/1Stue/2Sofabord/vintagemosaikkbord.jpeg',
        description: 'Unikt sofabord med unik topp. Bordet har lekre og unike smijernsdetaljer og freshe farger mixet inn i toppen. Dette bør man slite med å finne flere av. Produsert i Rwanda ca 1970.',
        measures: 'Høyde: 40cm. Lengde: 100cm. Dybde: 60cm. ',
        color: ['Svart', 'Smijern'],
        country: 'Rwanda',
        year: '1970',
        productQuantity: 0,
    },
    {
        title: 'Rundt sofabord',
        price: 4499,
        stock: 2,
        totalProducts: 2,
        category: 'Stue',
        id: 125,
        parentId: 12,
        subCategory: 'Sofabord',
        img: 'TempBilder/1Stue/2Sofabord/loungebordvintage.jpeg',
        description: 'Rundt lite sofabord med solide bein i en fin fasong. Passer perfekt inn i en stue, på et gjesterom eller som avlastningsbord i biblioteket. Bordet er laget på Island ca 1985.',
        measures: 'Høyde: 34cm. Bredde: 50cm. Dybde: 50cm. ',
        color: ['Grå', 'Mørk Brun'],
        country: 'Island',
        year: '1985',
        productQuantity: 0,
    },
    {
        title: 'Sjeselong (Skinn)',
        price: 6799,
        stock: 2,
        totalProducts: 2,
        category: 'Stue',
        id: 133,
        parentId: 13,
        subCategory: 'Sjeselong',
        img: 'TempBilder/1Stue/3Sjeselong/vintagesjesbrownleather.jpeg',
        description: 'Fin sjeselong i skinn, lett å vedlikeholde. Pent brukt, men veldig lite brukt. God å sitte i og viser kvalitet. Laget i Skottland, og lansert i 1990.',
        measures: 'Høyde: 90cm. Bredde: 50cm. Lengde: 120cm.',
        color: ['Brun', 'Skinn'],
        country: 'Skottland',
        year: '1990',
        productQuantity: 0,
    },
    {
        title: 'Mønstrete Sjeselong',
        price: 4599,
        stock: 2,
        totalProducts: 2,
        category: 'Stue',
        id: 130,
        parentId: 13,
        subCategory: 'Sjeselong',
        img: 'TempBilder/1Stue/3Sjeselong/sjespattern.jpeg',
        description: 'Mønstrete sjeselong, pent brukt og i god stand. Den har stått på et gjesterom. Her får du et klassisk 80-talls møbel. Den er laget i England og lansert ca 1983.',
        measures: 'Høyde: 34cm. Lengde: 110cm. Bredde: 45cm.',
        color: ['Blå', 'Mønstrete'],
        country: 'England',
        year: '1983',
        productQuantity: 0,
    },
    {
        title: 'Rød Eldre Sjeselong',
        price: 2499,
        stock: 3,
        totalProducts: 3,
        category: 'Stue',
        id: 131,
        parentId: 13,
        subCategory: 'Sjeselong',
        img: 'TempBilder/1Stue/3Sjeselong/sjesredold.jpeg',
        description: 'Rød, skikkelig retro sjeselong. Stått på et kontor, så omtrent ikke brukt. Veldig pen stand. God å sitte i. Laget i Sverige ca 1984.',
        measures: 'Høyde: 80. Lengde: 120cm. Bredde: 75cm.',
        color: ['Rød'],
        country: 'Sverige',
        year: '1984',
        productQuantity: 0,
    },
    {
        title: 'Kommode',
        price: 5499,
        stock: 2,
        totalProducts: 2,
        category: 'Spiserom',
        id: 126,
        parentId: 24,
        subCategory: 'Kommoder',
        img: 'TempBilder/1Stue/4Kommoder/skjenkvintageblue.jpeg',
        description: 'Fin kommode i god stand. Stått pent oppbevart. Fin plass inni, så det er mye plass til oppbevaring. Et fint stykke kunst i stua. Laget i Finland og utgitt i 1990.',
        measures: 'Høyde: 80cm. Lengde: 110cm. Dybde: 40cm. ',
        color: ['Treverk'],
        country: 'Finland',
        year: '1990',
        productQuantity: 0,
    },
    {
        title: 'Kommode <br> (9 Skuffer)',
        price: 5899,
        stock: 2,
        totalProducts: 2,
        category: 'Spiserom',
        id: 127,
        parentId: 24,
        subCategory: 'Kommoder',
        img: 'TempBilder/1Stue/4Kommoder/vintagekommodeskuffer.webp',
        description: 'Røff kommode med god plass til oppbevaring. 9 fine skuffer. Pen stand og et solid møbel som vil vare lenge. Den er produsert i Italia og lansert i 1998.',
        measures: 'Høyde: 100cm. Lengde: 110cm. Dybde: 45cm. ',
        color: ['Brun'],
        country: 'Italia',
        year: '1998',
        productQuantity: 0,
    },
    {
        title: 'Retro Kommode <br> (8 Skuffer)',
        price: 3499,
        stock: 2,
        totalProducts: 2,
        category: 'Spiserom',
        id: 129,
        parentId: 24,
        subCategory: 'Kommoder',
        img: 'TempBilder/1Stue/4Kommoder/whitesjenk.jpeg',
        description: 'Fin retro kommode. 8 skuffer gjør at man har god plass ift oppbevaring. Passer for eksempel fint på soverommet. Den er laget i Danmark og lansert i 1982.',
        measures: 'Høyde: 90cm. Lengde: 110cm. Dybde: 60cm. ',
        color: ['Hvit'],
        country: 'Denmark',
        year: '1982',
        productQuantity: 0,
    }
];


